;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/governance/templates.lisp
;;;;
;;;; Content generators for all governance files.
;;;; Each function returns a string; Consfigurator file:has-content writes it.
;;;; No YAML, no heredocs, no string surgery.

(defpackage #:dps.meta.governance
  (:use #:cl)
  (:export #:claude-md-content
           #:contributing-content
           #:security-content
           #:code-of-conduct-content
           #:support-content
           #:codeowners-content
           #:changelog-stub-content))

(in-package #:dps.meta.governance)

;;; ---------------------------------------------------------------------------
;;; CLAUDE.md
;;; ---------------------------------------------------------------------------

(defun claude-md-content (application meta-type version branch licence)
  "Return CLAUDE.md content for a target repo."
  (format nil
    "<!-- SPDX-License-Identifier: ~A -->~%~
     <!-- Generated by dps-meta. Re-generate: uses: denzuko/dps-meta@v1 -->~%~%~
     # CLAUDE.md — ~A~%~%~
     ## Project identity~%~%~
     | Key | Value |~%~
     |-----|-------|~%~
     | application | `~A` |~%~
     | type | `~A` |~%~
     | version | `~A` |~%~
     | default branch | `~A` |~%~
     | licence | `~A` |~%~
     | organisation | `daplanet` |~%~%~
     ## Standards stack~%~%~
     This repo carries the full denzuko organisation standards scaffold:~%~%~
     - **SLSA Level 3** provenance via `slsa-framework/slsa-github-generator`~%~
     - **OPA/Rego** policy gates in `policy/`~%~
     - **CycloneDX SBOM** via `cdxgen`, scanned by `osv-scanner`~%~
     - **net.matrix CMDB** identity baked into binary at compile time~%~
     - **BSD 2-Clause** licence throughout~%~%~
     ## BDD workflow~%~%~
     1. Write Rego gate first (`policy/`)~%~
     2. Write specs (FiveAM / BATS) before implementation~%~
     3. Write implementation~%~
     4. Update `CHANGELOG.md`~%~
     5. Build and verify binary~%~
     6. PR → merge → tag (semver)~%~%~
     ## Semver rules~%~%~
     - `MAJOR` — public API / interface break only~%~
     - `MINOR` — new non-breaking capability~%~
     - `PATCH` — everything else; patch freely exceeds 100~%~
     - **Never** bump MAJOR for restructuring~%~%~
     ## Build~%~%~
     See `nob.c` (C99 repos) or `qlot exec ros build` (Lisp repos).~%~
     Never use bare `ros build`; `qlot` pins the dependency set.~%~%~
     ## Do not~%~%~
     - Edit generated files by hand — re-run `dps-meta` instead~%~
     - Add Airflow, Celery, Redis, or Nginx~%~
     - Use `system()`, `popen()`, or `exec*()` in C99 code~%~
     - Write code before writing the spec and Rego gate~%"
    licence application application meta-type version branch licence))

;;; ---------------------------------------------------------------------------
;;; CONTRIBUTING.md
;;; ---------------------------------------------------------------------------

(defun contributing-content (application)
  (format nil
    "<!-- SPDX-License-Identifier: BSD-2-Clause -->~%~
     <!-- Generated by dps-meta. Re-generate: uses: denzuko/dps-meta@v1 -->~%~%~
     # Contributing to ~A~%~%~
     ## Before you open a PR~%~%~
     1. Check that the relevant Rego gate in `policy/` covers your change.~%~
        If it does not, write the gate first.~%~
     2. Write or update specs (FiveAM / BATS) before implementation.~%~
     3. Run `opa check policy/` locally.~%~
     4. All CI jobs must be green; no exceptions.~%~%~
     ## Commit message format~%~%~
     ```~%~
     <type>(<scope>): <subject>~%~%~
     <body>~%~
     ```~%~%~
     Types: `feat` | `fix` | `refactor` | `test` | `docs` | `chore`~%~%~
     ## Semver~%~%~
     PATCH freely exceeds 100. Never bump MAJOR for restructuring.~%~
     See `CLAUDE.md` for full semver rules.~%~%~
     ## Licence~%~%~
     All contributions are BSD 2-Clause unless otherwise noted in the file.~%~
     Add `SPDX-License-Identifier: BSD-2-Clause` to every new file.~%"
    application))

;;; ---------------------------------------------------------------------------
;;; SECURITY.md
;;; ---------------------------------------------------------------------------

(defun security-content (application)
  (format nil
    "<!-- SPDX-License-Identifier: BSD-2-Clause -->~%~
     <!-- Generated by dps-meta. Re-generate: uses: denzuko/dps-meta@v1 -->~%~%~
     # Security Policy — ~A~%~%~
     ## Reporting a vulnerability~%~%~
     Do **not** open a public issue.~%~%~
     Email: security@dapla.net~%~
     Subject: `[SECURITY] ~A — <brief description>`~%~%~
     We acknowledge within 72 hours and aim to patch within 14 days~%~
     for confirmed critical/high severity findings.~%~%~
     ## Supply chain~%~%~
     This repo ships SLSA Level 3 provenance attestations.~%~
     Verify any release artifact with:~%~%~
     ```sh~%~
     slsa-verifier verify-artifact <artifact> \\~%~
       --provenance-path <artifact>.intoto.jsonl \\~%~
       --source-uri github.com/denzuko/~A~%~
     ```~%~%~
     ## CVE scanning~%~%~
     Every CI run scans the CycloneDX SBOM with `osv-scanner`.~%~
     Critical/High CVEs block merge.~%"
    application application application))

;;; ---------------------------------------------------------------------------
;;; CODE_OF_CONDUCT.md
;;; ---------------------------------------------------------------------------

(defun code-of-conduct-content ()
  (format nil
    "<!-- SPDX-License-Identifier: BSD-2-Clause -->~%~
     <!-- Generated by dps-meta. Re-generate: uses: denzuko/dps-meta@v1 -->~%~%~
     # Code of Conduct~%~%~
     This project adopts the Contributor Covenant v2.1.~%~%~
     https://www.contributor-covenant.org/version/2/1/code_of_conduct/~%~%~
     ## Enforcement~%~%~
     Instances of abusive, harassing, or otherwise unacceptable behaviour~%~
     may be reported to: conduct@dapla.net~%~
     All reports will be reviewed and investigated promptly and fairly.~%"))

;;; ---------------------------------------------------------------------------
;;; SUPPORT.md
;;; ---------------------------------------------------------------------------

(defun support-content (application)
  (format nil
    "<!-- SPDX-License-Identifier: BSD-2-Clause -->~%~
     <!-- Generated by dps-meta. Re-generate: uses: denzuko/dps-meta@v1 -->~%~%~
     # Support — ~A~%~%~
     ## Community~%~%~
     - Albany 2600 — second Friday, Washington Ave Armory lobby~%~
     - Hacker Public Radio — https://hackerpublicradio.org~%~
     - aNONradio — https://anonradio.net~%~%~
     ## Issues~%~%~
     Open a GitHub issue for bugs and feature requests.~%~
     Security issues: see `SECURITY.md`.~%~%~
     ## Response time~%~%~
     This is a one-person MSSP. Best-effort; no SLA on open-source work.~%"
    application))

;;; ---------------------------------------------------------------------------
;;; .github/CODEOWNERS
;;; ---------------------------------------------------------------------------

(defun codeowners-content ()
  (format nil
    "# CODEOWNERS~%~
     # Generated by dps-meta. Re-generate: uses: denzuko/dps-meta@v1~%~%~
     # Default: Den Zuko owns everything~%~
     * @denzuko~%~%~
     # Policy gates require explicit review~%~
     /policy/ @denzuko~%~%~
     # CI workflows require explicit review~%~
     /.github/workflows/ @denzuko~%"))

;;; ---------------------------------------------------------------------------
;;; CHANGELOG.md stub
;;; ---------------------------------------------------------------------------

(defun changelog-stub-content (application version)
  (format nil
    "<!-- SPDX-License-Identifier: BSD-2-Clause -->~%~
     <!-- Generated by dps-meta. Re-generate: uses: denzuko/dps-meta@v1 -->~%~%~
     # Changelog — ~A~%~%~
     All notable changes to this project are documented here.~%~
     Format: [Keep a Changelog](https://keepachangelog.com/en/1.1.0/)~%~
     Versioning: [Semantic Versioning](https://semver.org/spec/v2.0.0.html)~%~%~
     ## [Unreleased]~%~%~
     ## [~A] — ~A~%~%~
     ### Added~%~%~
     - Initial scaffold generated by dps-meta~%~
     - SLSA Level 3 provenance workflow~%~
     - OPA/Rego policy gates~%~
     - CycloneDX SBOM generation~%~
     - net.matrix CMDB identity~%"
    application version
    (multiple-value-bind (s m h d mo y)
        (decode-universal-time (get-universal-time))
      (declare (ignore s m h))
      (format nil "~4,'0D-~2,'0D-~2,'0D" y mo d))))
