;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/attestation/specs.lisp
;;;;
;;;; FiveAM attestation specs for dps-meta generated output.
;;;; These run AGAINST the generated files in a test checkout, not against
;;;; the generator internals.  The generator is correct when all specs pass.
;;;;
;;;; Execution:
;;;;   (ql:quickload :dps-meta-test)
;;;;   (fiveam:run! 'dps.meta.attestation:all)
;;;;
;;;; BDD rule: every spec here was written before the corresponding
;;;; generator function.  Do not add implementation before adding a spec.

(defpackage #:dps.meta.attestation
  (:use #:cl #:fiveam)
  (:export #:all))

(in-package #:dps.meta.attestation)

;;; ---------------------------------------------------------------------------
;;; Test suite root
;;; ---------------------------------------------------------------------------

(def-suite all
  :description "dps-meta generated-output attestation specs")

;;; ---------------------------------------------------------------------------
;;; Helpers
;;; ---------------------------------------------------------------------------

(defun test-checkout-path ()
  "Return the path of the test checkout directory.
   Set DPS_META_TEST_CHECKOUT env var to override; defaults to a temp dir
   populated by the BATS integration tests."
  (or (uiop:getenv "DPS_META_TEST_CHECKOUT")
      (error "DPS_META_TEST_CHECKOUT not set — run via BATS integration suite")))

(defun generated-file (relative-path)
  "Return an absolute pathname for RELATIVE-PATH under the test checkout."
  (merge-pathnames relative-path
                   (uiop:ensure-directory-pathname (test-checkout-path))))

(defun file-exists-p* (relative-path)
  "True if the generated file at RELATIVE-PATH exists."
  (uiop:file-exists-p (generated-file relative-path)))

(defun file-contains-p (relative-path substring)
  "True if the generated file at RELATIVE-PATH contains SUBSTRING."
  (let ((content (uiop:read-file-string (generated-file relative-path))))
    (search substring content)))

(defun yaml-key-present-p (relative-path key)
  "Crude but zero-dependency check: key appears on its own line in the YAML file."
  (file-contains-p relative-path (concatenate 'string key ":")))

;;; ---------------------------------------------------------------------------
;;; Suite: common governance files (all repo types)
;;; ---------------------------------------------------------------------------

(def-suite governance
  :description "Governance files generated for every repo type"
  :in all)

(in-suite governance)

(test claude-md-exists
  "CLAUDE.md must be generated"
  (is (file-exists-p* "CLAUDE.md")))

(test claude-md-has-spdx
  "CLAUDE.md must carry the BSD-2-Clause SPDX identifier"
  (is (file-contains-p "CLAUDE.md" "SPDX-License-Identifier: BSD-2-Clause")))

(test contributing-exists
  "CONTRIBUTING.md must be generated"
  (is (file-exists-p* "CONTRIBUTING.md")))

(test security-exists
  "SECURITY.md must be generated"
  (is (file-exists-p* "SECURITY.md")))

(test code-of-conduct-exists
  "CODE_OF_CONDUCT.md must be generated"
  (is (file-exists-p* "CODE_OF_CONDUCT.md")))

(test support-exists
  "SUPPORT.md must be generated"
  (is (file-exists-p* "SUPPORT.md")))

(test codeowners-exists
  ".github/CODEOWNERS must be generated"
  (is (file-exists-p* ".github/CODEOWNERS")))

(test changelog-stub-exists
  "CHANGELOG.md must be generated"
  (is (file-exists-p* "CHANGELOG.md")))

;;; ---------------------------------------------------------------------------
;;; Suite: CI/CD workflow files
;;; ---------------------------------------------------------------------------

(def-suite ci-workflows
  :description "CI/CD workflow files generated by 40ants/CI classes"
  :in all)

(in-suite ci-workflows)

(test ci-yml-exists
  ".github/workflows/ci.yml must be generated"
  (is (file-exists-p* ".github/workflows/ci.yml")))

(test slsa-yml-exists
  ".github/workflows/slsa.yml must be generated"
  (is (file-exists-p* ".github/workflows/slsa.yml")))

(test ci-yml-has-opa-gate
  "ci.yml must reference the OPA gate job"
  (is (yaml-key-present-p ".github/workflows/ci.yml" "opa-gate")))

(test ci-yml-has-sbom-job
  "ci.yml must reference the SBOM job"
  (is (yaml-key-present-p ".github/workflows/ci.yml" "sbom")))

(test slsa-yml-has-provenance
  "slsa.yml must reference provenance generation"
  (is (yaml-key-present-p ".github/workflows/slsa.yml" "provenance")))

(test slsa-yml-pinned-runner
  "slsa.yml must pin to ubuntu-24.04"
  (is (file-contains-p ".github/workflows/slsa.yml" "ubuntu-24.04")))

;;; ---------------------------------------------------------------------------
;;; Suite: Rego policy files
;;; ---------------------------------------------------------------------------

(def-suite policy-files
  :description "OPA/Rego policy gates generated into the target repo"
  :in all)

(in-suite policy-files)

(test slsa-rego-exists
  "policy/slsa.rego must be generated"
  (is (file-exists-p* "policy/slsa.rego")))

(test slsa-rego-has-package
  "policy/slsa.rego must declare package dps.meta.slsa or repo-specific package"
  (is (file-contains-p "policy/slsa.rego" "package")))

(test slsa-rego-has-allow
  "policy/slsa.rego must define an allow rule"
  (is (file-contains-p "policy/slsa.rego" "allow")))

(test slsa-rego-has-violation
  "policy/slsa.rego must define a violation set"
  (is (file-contains-p "policy/slsa.rego" "violation")))

;;; ---------------------------------------------------------------------------
;;; Suite: C99 identity header (c99-binary and c99-header types only)
;;; ---------------------------------------------------------------------------

(def-suite c99-identity
  :description "matrix_id.h generated for C99 repo types"
  :in all)

(in-suite c99-identity)

(test matrix-id-h-exists
  "matrix_id.h must be generated for c99 repo types"
  (is (file-exists-p* "matrix_id.h")))

(test matrix-id-h-has-guard
  "matrix_id.h must have an include guard"
  (is (file-contains-p "matrix_id.h" "#ifndef MATRIX_ID_H")))

(test matrix-id-h-has-organization
  "matrix_id.h must define NET_MATRIX_ORGANIZATION"
  (is (file-contains-p "matrix_id.h" "NET_MATRIX_ORGANIZATION")))

(test matrix-id-h-has-application
  "matrix_id.h must define NET_MATRIX_APPLICATION"
  (is (file-contains-p "matrix_id.h" "NET_MATRIX_APPLICATION")))

(test matrix-id-h-has-role
  "matrix_id.h must define NET_MATRIX_ROLE"
  (is (file-contains-p "matrix_id.h" "NET_MATRIX_ROLE")))

(test matrix-id-h-has-version
  "matrix_id.h must define NET_MATRIX_VERSION matching meta.version"
  (is (file-contains-p "matrix_id.h" "NET_MATRIX_VERSION")))

(test matrix-id-h-has-spdx
  "matrix_id.h must carry SPDX-License-Identifier"
  (is (file-contains-p "matrix_id.h" "SPDX-License-Identifier")))

;;; ---------------------------------------------------------------------------
;;; Suite: Lisp identity module (lisp-actor type only)
;;; ---------------------------------------------------------------------------

(def-suite lisp-identity
  :description "src/matrix-id.lisp generated for lisp-actor repos"
  :in all)

(in-suite lisp-identity)

(test matrix-id-lisp-exists
  "src/matrix-id.lisp must be generated for lisp-actor repos"
  (is (file-exists-p* "src/matrix-id.lisp")))

(test matrix-id-lisp-has-package
  "src/matrix-id.lisp must define a package"
  (is (file-contains-p "src/matrix-id.lisp" "defpackage")))

(test matrix-id-lisp-has-organization
  "src/matrix-id.lisp must define +organization+ constant"
  (is (file-contains-p "src/matrix-id.lisp" "+organization+")))

(test matrix-id-lisp-has-application
  "src/matrix-id.lisp must define +application+ constant"
  (is (file-contains-p "src/matrix-id.lisp" "+application+")))

(test matrix-id-lisp-has-role
  "src/matrix-id.lisp must define +role+ constant"
  (is (file-contains-p "src/matrix-id.lisp" "+role+")))

(test matrix-id-lisp-has-version
  "src/matrix-id.lisp must define +version+ constant"
  (is (file-contains-p "src/matrix-id.lisp" "+version+")))

;;; ---------------------------------------------------------------------------
;;; Suite: net.matrix label consistency
;;; ---------------------------------------------------------------------------

(def-suite label-consistency
  :description "net.matrix values in generated files must be mutually consistent"
  :in all)

(in-suite label-consistency)

(test ci-yml-has-matrix-labels
  "ci.yml must reference net.matrix labels in OCI image build step"
  (is (file-contains-p ".github/workflows/ci.yml" "net.matrix")))

;;; ---------------------------------------------------------------------------
;;; Suite: SLSA Rego gate self-check
;;; ---------------------------------------------------------------------------

(def-suite slsa-gate-self-check
  :description "The generated policy/slsa.rego passes OPA syntax check"
  :in all)

(in-suite slsa-gate-self-check)

(test slsa-rego-opa-check
  "policy/slsa.rego must pass `opa check`"
  (let* ((rego-path (namestring (generated-file "policy/slsa.rego")))
         (result (uiop:run-program
                   (list "opa" "check" rego-path)
                   :output :string
                   :error-output :string
                   :ignore-error-status t)))
    ;; opa check exits 0 on success; non-zero on parse/compile error
    (is (string= "" result)
        "opa check produced output (errors): ~A" result)))
