;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/attestation/upstream-specs.lisp
;;;;
;;;; FiveAM specs verifying that dps/meta correctly fetches and delivers
;;;; canonical content from cispec.org.
;;;;
;;;; These specs run against a mock HTTP server or the live site depending
;;;; on whether CISPEC_OFFLINE=1 is set in the environment.
;;;; In CI, CISPEC_OFFLINE=1 is set and the mock fixtures are used.

(defpackage #:dps.meta.attestation.upstream
  (:use #:cl #:fiveam)
  (:import-from #:dps.meta.identity.upstream
                #:*cispec-base-url*
                #:fetch-matrix-id-h
                #:fetch-matrix-id-lisp
                #:extract-code-block
                #:extract-lisp-block)
  (:import-from #:dps.meta.policy.upstream
                #:fetch-gate
                #:extract-rego-block)
  (:export #:run-upstream-specs))

(in-package #:dps.meta.attestation.upstream)

(def-suite upstream-suite
  :description "cispec.org upstream fetch integration")

(in-suite upstream-suite)

;;; ----------------------------------------------------------------
;;; Fixtures — minimal synthetic responses for offline testing
;;; ----------------------------------------------------------------

(defparameter *mock-matrix-id-h*
  "```c
/* SPDX-License-Identifier: BSD-2-Clause */
volatile const char CISPEC_ID_ORGANIZATION[] = \"org.cispec.organization=\" CISPEC_ORGANIZATION;
volatile const char CISPEC_ID_APPLICATION[]  = \"org.cispec.application=\" CISPEC_APPLICATION;
volatile const char CISPEC_ID_VERSION[]      = \"org.cispec.version=\" CISPEC_VERSION;
```")

(defparameter *mock-matrix-id-lisp*
  "```lisp
(defpackage #:org.cispec.matrix-id (:use #:cl) (:export #:label-set))
(in-package #:org.cispec.matrix-id)
(defconstant +organization+ (uiop:getenv \"CISPEC_ORGANIZATION\"))
```")

(defparameter *mock-attribution-rego*
  "```rego
# SPDX-License-Identifier: BSD-2-Clause
package cispec.attribution
cispec_version := \"1.0\"
deny contains msg if { not input.labels[\"org.cispec.organization\"]; msg := \"missing\" }
```")

(defparameter *mock-slsa-rego*
  "```rego
# SPDX-License-Identifier: BSD-2-Clause
package cispec.slsa.provenance
cispec_version := \"1.0\"
deny contains msg if { not input.predicateType; msg := \"missing predicateType\" }
```")

;;; ----------------------------------------------------------------
;;; Code block extraction
;;; ----------------------------------------------------------------

(test extract-c-block
  (let ((result (extract-code-block *mock-matrix-id-h*)))
    (is (stringp result))
    (is (str:containsp "CISPEC_ID_ORGANIZATION" result))
    (is (str:containsp "volatile const char" result))))

(test extract-lisp-block-test
  (let ((result (extract-lisp-block *mock-matrix-id-lisp*)))
    (is (stringp result))
    (is (str:containsp "org.cispec.matrix-id" result))
    (is (str:containsp "defpackage" result))))

(test extract-rego-block-test
  (let ((result (extract-rego-block *mock-attribution-rego*)))
    (is (stringp result))
    (is (str:containsp "package cispec.attribution" result))
    (is (str:containsp "cispec_version" result))))

(test extract-returns-nil-on-no-match
  (is (null (extract-code-block "no code block here")))
  (is (null (extract-lisp-block "no lisp block here")))
  (is (null (extract-rego-block "no rego block here"))))

;;; ----------------------------------------------------------------
;;; matrix_id.h interpolation — offline mode uses mock
;;; ----------------------------------------------------------------

(defun offline-p ()
  (let ((val (uiop:getenv "CISPEC_OFFLINE")))
    (and val (not (string= val "")))))

(defmacro with-mock-fetch ((var mock-string) &body body)
  "Rebind dps.meta.identity.upstream:fetch-url to return MOCK-STRING
   and evaluate BODY. Used for offline testing."
  `(let ((,var ,mock-string))
     (cl-mock:with-mocks ()
       (cl-mock:if-called 'dps.meta.identity.upstream:fetch-url
                          (lambda (url) (declare (ignore url)) ,var))
       ,@body)))

(test matrix-id-h-content-has-required-strings
  (when (offline-p)
    (with-mock-fetch (mock *mock-matrix-id-h*)
      (let ((content (fetch-matrix-id-h "test-app" "test-role" "1.0.0")))
        (is (stringp content))
        ;; Generated preamble
        (is (str:containsp "Generated by dps/meta" content))
        (is (str:containsp "cispec.org/spec/matrix_id.h" content))
        ;; Interpolated defines
        (is (str:containsp "test-app" content))
        (is (str:containsp "1.0.0" content))
        ;; Canonical volatile const pattern
        (is (str:containsp "volatile const char" content))))))

(test matrix-id-lisp-content-has-package
  (when (offline-p)
    (with-mock-fetch (mock *mock-matrix-id-lisp*)
      (let ((content (fetch-matrix-id-lisp :note-application "test-app")))
        (is (stringp content))
        (is (str:containsp "Generated by dps/meta" content))
        (is (str:containsp "org.cispec.matrix-id" content))))))

;;; ----------------------------------------------------------------
;;; Gate fetch — offline mode uses mock
;;; ----------------------------------------------------------------

(test gate-fetch-attribution-has-package
  (when (offline-p)
    (with-mock-fetch (mock *mock-attribution-rego*)
      (let ((content (fetch-gate "cispec/attribution.rego")))
        (is (stringp content))
        (is (str:containsp "package cispec.attribution" content))
        (is (str:containsp "cispec_version" content))))))

(test gate-fetch-slsa-has-package
  (when (offline-p)
    (with-mock-fetch (mock *mock-slsa-rego*)
      (let ((content (fetch-gate "slsa/provenance.rego")))
        (is (stringp content))
        (is (str:containsp "package cispec.slsa.provenance" content))))))

(test gate-has-spdx-header
  (when (offline-p)
    (with-mock-fetch (mock *mock-attribution-rego*)
      (let ((content (fetch-gate "cispec/attribution.rego")))
        (is (str:containsp "SPDX-License-Identifier: BSD-2-Clause" content))))))

(test gate-has-cispec-version
  (when (offline-p)
    (with-mock-fetch (mock *mock-attribution-rego*)
      (let ((content (fetch-gate "cispec/attribution.rego")))
        (is (str:containsp "cispec_version" content))))))

;;; ----------------------------------------------------------------
;;; Entry point
;;; ----------------------------------------------------------------

(defun run-upstream-specs ()
  "Run the upstream fetch specs. Returns T if all pass."
  (let ((results (run 'upstream-suite)))
    (fiveam:explain! results)
    (every #'fiveam::test-passed-p results)))
