;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/policy/ast.lisp
;;;;
;;;; AST forbidden-call Rego gate content for dps/meta.
;;;; Delegates to dps.meta.policy.upstream — gate fetched from
;;;; https://cispec.org/gates/ast/forbidden-calls.rego at scaffold time.
;;;;
;;;; Public API unchanged: (ast-rego-content application)
;;;; Callers in dps/meta/properties/c99-binary.lisp and c99-header.lisp
;;;; require no changes.

(defpackage #:dps.meta.policy.ast
  (:use #:cl #:dps.meta.policy.upstream)
  (:export #:ast-rego-content))

(in-package #:dps.meta.policy.ast)

(defun ast-rego-content (application)
  "Return the content for policy/ast.rego in the target repo.

   Fetches the canonical gate from
   https://cispec.org/gates/ast/forbidden-calls.rego.
   APPLICATION is recorded in a header comment."
  (str:concat
   (format nil "# Generated by dps/meta from https://cispec.org/gates/ast/forbidden-calls.rego~%~
                # Target application: ~A~%~
                # Do not edit — regenerate with: dps-meta~%~%"
           application)
   (fetch-gate "ast/forbidden-calls.rego")))
