;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/policy/ast.lisp
;;;;
;;;; Generates policy/ast.rego for C99 repo types.
;;;; Gate: structural AST rules — arena usage patterns, ownership model.

(defpackage #:dps.meta.policy.ast
  (:use #:cl)
  (:export #:ast-rego-content))

(in-package #:dps.meta.policy.ast)

(defun ast-rego-content (application)
  "Return the full text of policy/ast.rego."
  (declare (ignore application))
  (format nil
    "# SPDX-License-Identifier: BSD-2-Clause~%~
     # policy/ast.rego~%~
     # Generated by dps-meta. Do not hand-edit.~%~
     # Gate: C99 AST structural rules for denzuko org.~%~%~
     package dps.meta.ast~%~%~
     import future.keywords.if~%~
     import future.keywords.in~%~%~
     default allow := false~%~%~
     allow if { count(violation) == 0 }~%~%~
     # Arena must be zero-initialised (tsoding/arena.h pattern)~%~
     violation contains msg if {~%~
         some finding in input.runs[_].results~%~
         finding.ruleId == \"arena-not-zeroed\"~%~
         msg := \"arena allocation without zero-init — use Arena a = {0}\"~%~
     }~%~%~
     # No snapshot/rewind bypass~%~
     violation contains msg if {~%~
         some finding in input.runs[_].results~%~
         finding.ruleId == \"arena-scratch-direct\"~%~
         msg := \"direct arena scratch — use arena_save/arena_rewind pattern\"~%~
     }~%~%~
     # rc.h shared ownership: no raw pointer aliasing~%~
     violation contains msg if {~%~
         some finding in input.runs[_].results~%~
         finding.ruleId == \"rc-raw-alias\"~%~
         msg := \"raw pointer alias of rc-owned value — use rc_clone\"~%~
     }~%"))
