;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/policy/c-quality.lisp
;;;;
;;;; C99 quality Rego gate content for dps/meta.
;;;; Delegates to dps.meta.policy.upstream — gate fetched from
;;;; https://cispec.org/gates/c-quality/attribution.rego at scaffold time.
;;;;
;;;; Public API unchanged: (c-quality-rego-content application)
;;;; Callers in dps/meta/properties/c99-binary.lisp and c99-header.lisp
;;;; require no changes.

(defpackage #:dps.meta.policy.c-quality
  (:use #:cl #:dps.meta.policy.upstream)
  (:export #:c-quality-rego-content))

(in-package #:dps.meta.policy.c-quality)

(defun c-quality-rego-content (application)
  "Return the content for policy/c_quality.rego in the target repo.

   Fetches the canonical gate from
   https://cispec.org/gates/c-quality/attribution.rego.
   APPLICATION is recorded in a header comment."
  (str:concat
   (format nil "# Generated by dps/meta from https://cispec.org/gates/c-quality/attribution.rego~%~
                # Target application: ~A~%~
                # Do not edit — regenerate with: dps-meta~%~%"
           application)
   (fetch-gate "c-quality/attribution.rego")))
