;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/policy/c-quality.lisp
;;;;
;;;; Generates policy/c_quality.rego for C99 repo types.
;;;; Gate: no banned functions (system, popen, exec*), no static JSON strings,
;;;; no scratch arenas.  Evaluated against clang-tidy SARIF output.

(defpackage #:dps.meta.policy.c-quality
  (:use #:cl)
  (:export #:c-quality-rego-content))

(in-package #:dps.meta.policy.c-quality)

(defun c-quality-rego-content (application)
  "Return the full text of policy/c_quality.rego."
  (declare (ignore application))
  (format nil
    "# SPDX-License-Identifier: BSD-2-Clause~%~
     # policy/c_quality.rego~%~
     # Generated by dps-meta. Do not hand-edit.~%~
     # Gate: C99 code quality rules for denzuko org.~%~%~
     package dps.meta.c_quality~%~%~
     import future.keywords.if~%~
     import future.keywords.in~%~%~
     # Functions banned outright in all C99 repos~%~
     banned_functions := {~%~
         \"system\", \"popen\",~%~
         \"execl\", \"execle\", \"execlp\",~%~
         \"execv\", \"execve\", \"execvp\", \"execvpe\"~%~
     }~%~%~
     default allow := false~%~%~
     allow if { count(violation) == 0 }~%~%~
     violation contains msg if {~%~
         some finding in input.runs[_].results~%~
         some location in finding.locations~%~
         some call in location.logicalLocations~%~
         call.name in banned_functions~%~
         msg := sprintf(\"banned function call: %%v at %%v\",~%~
                        [call.name, location.physicalLocation.artifactLocation.uri])~%~
     }~%~%~
     violation contains msg if {~%~
         some finding in input.runs[_].results~%~
         finding.ruleId == \"static-json-string\"~%~
         msg := \"static const char[] JSON string detected — use dict/object emission\"~%~
     }~%"))
