;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/policy/slsa.lisp
;;;;
;;;; SLSA Rego gate content for dps/meta.
;;;; Delegates to dps.meta.policy.upstream — gate fetched from
;;;; https://cispec.org/gates/slsa/provenance.rego at scaffold time.
;;;;
;;;; Public API unchanged: (slsa-rego-content application)
;;;; Callers in dps/meta/properties/common.lisp require no changes.

(defpackage #:dps.meta.policy.slsa
  (:use #:cl #:dps.meta.policy.upstream)
  (:export #:slsa-rego-content))

(in-package #:dps.meta.policy.slsa)

(defun slsa-rego-content (application)
  "Return the content for policy/slsa.rego in the target repo.

   Fetches the canonical gate from https://cispec.org/gates/slsa/provenance.rego.
   APPLICATION is recorded in a header comment for traceability but the gate
   itself is application-agnostic — it verifies SLSA attestation structure."
  (str:concat
   (format nil "# Generated by dps/meta from https://cispec.org/gates/slsa/provenance.rego~%~
                # Target application: ~A~%~
                # Do not edit — regenerate with: dps-meta~%~%"
           application)
   (fetch-gate "slsa/provenance.rego")))
