;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/identity/c99.lisp
;;;;
;;;; Generates the content of matrix_id.h for C99 repo types.
;;;; All values sourced from git config meta.* keys, passed in as strings.
;;;; Single point of change for net.matrix namespace rescope:
;;;; update *namespace-prefix* and recompile.

(defpackage #:dps.meta.identity.c99
  (:use #:cl)
  (:export #:matrix-id-h-content))

(in-package #:dps.meta.identity.c99)

;;; ---------------------------------------------------------------------------
;;; Namespace — single point of change for org.cispec / org.cimatrix rescope
;;; ---------------------------------------------------------------------------

(defparameter *namespace-prefix* "NET_MATRIX"
  "C preprocessor prefix for all net.matrix identity constants.
   When namespace rescopes to org.cispec or org.cimatrix, change only here.
   Value maps to the label namespace: net.matrix.* → NET_MATRIX_*")

(defparameter *label-namespace* "net.matrix"
  "OCI label namespace string baked into the header comment.
   Update together with *namespace-prefix* on rescope.")

;;; ---------------------------------------------------------------------------
;;; Generator
;;; ---------------------------------------------------------------------------

(defun matrix-id-h-content (application role version organisation licence)
  "Return the full text of matrix_id.h.
   APPLICATION  — git config meta.application
   ROLE         — git config meta.role
   VERSION      — git config meta.version  (semver string)
   ORGANISATION — 'daplanet' (fixed for denzuko org)
   LICENCE      — git config meta.licence  (spdx identifier string)"
  (let ((guard (format nil "~A_H" *namespace-prefix*))
        (pfx   *namespace-prefix*)
        (ns    *label-namespace*))
    (format nil
      "/* SPDX-License-Identifier: ~A */~%~
       /* matrix_id.h~%~
        * Generated by dps-meta. Do not hand-edit.~%~
        * Re-generate: uses: denzuko/dps-meta@v1~%~
        *~%~
        * ~A identity constants baked into binary at compile time.~%~
        * Labels: ~A.*~%~
        */~%~%~
       #ifndef ~A~%~
       #define ~A~%~%~
       #define ~A_ORGANISATION \"~A\"~%~
       #define ~A_APPLICATION   \"~A\"~%~
       #define ~A_ROLE          \"~A\"~%~
       #define ~A_VERSION       \"~A\"~%~%~
       /* Composite label strings for OCI image annotations */~%~
       #define ~A_LABEL_ORG     \"~A.organisation=~A\"~%~
       #define ~A_LABEL_APP     \"~A.application=~A\"~%~
       #define ~A_LABEL_ROLE    \"~A.role=~A\"~%~
       #define ~A_LABEL_VERSION \"~A.version=~A\"~%~%~
       #endif /* ~A */~%"
      licence
      ns ns
      guard guard
      pfx organisation
      pfx application
      pfx role
      pfx version
      pfx ns organisation
      pfx ns application
      pfx ns role
      pfx ns version
      guard)))
