;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/identity/lisp.lisp
;;;;
;;;; Generates the content of src/matrix-id.lisp for lisp-actor repo types.
;;;; Single point of change for net.matrix namespace rescope:
;;;; update *label-namespace* and recompile.

(defpackage #:dps.meta.identity.lisp
  (:use #:cl)
  (:export #:matrix-id-lisp-content))

(in-package #:dps.meta.identity.lisp)

;;; ---------------------------------------------------------------------------
;;; Namespace — single point of change for org.cispec / org.cimatrix rescope
;;; ---------------------------------------------------------------------------

(defparameter *label-namespace* "net.matrix"
  "Label namespace string.  Update on rescope.")

;;; ---------------------------------------------------------------------------
;;; Generator
;;; ---------------------------------------------------------------------------

(defun matrix-id-lisp-content (package-name application role version
                                organisation licence)
  "Return the full text of src/matrix-id.lisp.
   PACKAGE-NAME  — e.g. 'dps.meta.identity' (derived from meta.application)
   APPLICATION   — git config meta.application
   ROLE          — git config meta.role
   VERSION       — git config meta.version
   ORGANISATION  — 'daplanet'
   LICENCE       — spdx identifier string"
  (let ((ns *label-namespace*))
    (format nil
      ";;;; SPDX-License-Identifier: ~A~%~
       ;;;; src/matrix-id.lisp~%~
       ;;;; Generated by dps-meta. Do not hand-edit.~%~
       ;;;; Re-generate: uses: denzuko/dps-meta@v1~%~
       ;;;;~%~
       ;;;; ~A identity constants.  Single point of change for namespace rescope.~%~%~
       (defpackage #:~A.identity~%~
         (:use #:cl)~%~
         (:export #:+organisation+~%~
                  #:+application+~%~
                  #:+role+~%~
                  #:+version+~%~
                  #:label-string))~%~%~
       (in-package #:~A.identity)~%~%~
       (defconstant +organisation+ ~S~%~
         \"~A.organisation value.\")~%~%~
       (defconstant +application+ ~S~%~
         \"~A.application value.\")~%~%~
       (defconstant +role+ ~S~%~
         \"~A.role value.\")~%~%~
       (defconstant +version+ ~S~%~
         \"Semver string — must match meta.version git config.\")~%~%~
       (defun label-string (key value)~%~
         \"Return a ~A OCI label string: 'namespace.KEY=VALUE'.\"~%~
         (format nil \"~A.~~A=~~A\" key value))~%"
      licence
      ns
      package-name
      package-name
      organisation ns
      application ns
      role ns
      version
      ns ns)))
