;;;; SPDX-License-Identifier: BSD-2-Clause
;;;; dps/meta/identity/upstream.lisp
;;;;
;;;; Fetch canonical org.cispec identity headers from cispec.org.
;;;; Replaces inline string generation in c99.lisp and lisp.lisp.
;;;;
;;;; Called at scaffold-generation time (when dps-meta runs in the target
;;;; repo). Output is the fetched file content as a string, with repo-specific
;;;; preprocessor defines interpolated for the C99 case.
;;;;
;;;; cispec.org is the upstream source of truth. dps/meta no longer owns
;;;; the header content — it owns only the interpolation and delivery.

(defpackage #:dps.meta.identity.upstream
  (:use #:cl)
  (:export #:fetch-matrix-id-h
           #:fetch-matrix-id-lisp
           #:cispec-url
           #:*cispec-base-url*
           #:*cispec-spec-version*))

(in-package #:dps.meta.identity.upstream)

(defparameter *cispec-base-url*
  "https://cispec.org"
  "Canonical cispec.org base URL. Override for local testing.")

(defparameter *cispec-spec-version*
  "1.0"
  "cispec spec version dps/meta targets. Pins the upstream fetch.")

(defparameter *fetch-timeout-seconds*
  10
  "HTTP fetch timeout. Fail fast — do not hang a scaffold run.")

;;; ----------------------------------------------------------------
;;; URL construction
;;; ----------------------------------------------------------------

(defun cispec-url (path)
  "Return the full cispec.org URL for PATH (e.g. \"/spec/matrix_id.h\")."
  (str:concat *cispec-base-url* path))

;;; ----------------------------------------------------------------
;;; HTTP fetch — drakma, no new deps (already in qlfile via drakma)
;;; ----------------------------------------------------------------

(defun fetch-url (url)
  "Fetch URL and return the body as a string. Signals an error on failure."
  (multiple-value-bind (body status-code)
      (drakma:http-request url
                           :connection-timeout *fetch-timeout-seconds*
                           :read-timeout       *fetch-timeout-seconds*
                           :want-stream        nil
                           :force-string       t)
    (unless (= status-code 200)
      (error "cispec upstream fetch failed: ~A returned HTTP ~D" url status-code))
    body))

;;; ----------------------------------------------------------------
;;; matrix_id.h — fetch canonical header, strip Hugo frontmatter,
;;; extract the fenced code block, interpolate repo-specific defines.
;;; ----------------------------------------------------------------

(defun extract-code-block (markdown-body)
  "Extract the first ```c ... ``` fenced code block from MARKDOWN-BODY."
  (cl-ppcre:register-groups-bind (code)
      ("(?s)```c\\n(.*?)```" markdown-body)
    code))

(defun interpolate-h-defines (header-text application role version organisation licence)
  "Return HEADER-TEXT with the example define values replaced by repo-specific ones.
   The canonical header uses placeholder strings in its example block; we substitute
   those after extraction so the written file is immediately usable without -D flags."
  (declare (ignore role licence))   ; present in signature for future use
  ;; The canonical header uses #error guards — the generated file pre-populates
  ;; the defines above the #include so the target project gets a ready-to-use copy.
  ;; We prepend a generated preamble; the guard block stays intact.
  (str:concat
   (format nil "/* Generated by dps/meta from https://cispec.org/spec/matrix_id.h~%~
                 * cispec spec version: ~A~%~
                 * org.cispec.organization: ~A~%~
                 * org.cispec.application:  ~A~%~
                 * org.cispec.version:      ~A~%~
                 *~%~
                 * Do not edit — regenerate with: dps-meta~%~
                 */~%~
                 #ifndef CISPEC_ORGANIZATION~%~
                 #  define CISPEC_ORGANIZATION ~S~%~
                 #endif~%~
                 #ifndef CISPEC_ORGUNIT~%~
                 #  define CISPEC_ORGUNIT     \"dps\"~%~
                 #endif~%~
                 #ifndef CISPEC_APPLICATION~%~
                 #  define CISPEC_APPLICATION ~S~%~
                 #endif~%~
                 #ifndef CISPEC_VERSION~%~
                 #  define CISPEC_VERSION     ~S~%~
                 #endif~%~%"
           *cispec-spec-version*
           organisation
           application
           version
           organisation
           application
           version)
   header-text))

(defun fetch-matrix-id-h (application role version
                           &key (organisation "daplanet")
                                (licence "BSD-2-Clause"))
  "Fetch the canonical matrix_id.h from cispec.org, extract the C source,
   and return a string ready to write to the target repo's include path.

   The returned string is the complete header with a generated preamble
   pre-populating CISPEC_ORGANIZATION, CISPEC_APPLICATION, and CISPEC_VERSION
   for APPLICATION. The #error guards remain intact for any key left undefined."
  (let* ((url      (cispec-url "/spec/matrix_id-h/"))
         (markdown (fetch-url url))
         (code     (extract-code-block markdown)))
    (unless code
      (error "dps/meta: could not extract C code block from ~A" url))
    (interpolate-h-defines code application role version organisation licence)))

;;; ----------------------------------------------------------------
;;; matrix-id.lisp — fetch canonical SBCL module, extract code block,
;;; return as-is (env-or reads CISPEC_* at load time, no interpolation needed).
;;; ----------------------------------------------------------------

(defun fetch-matrix-id-lisp (&key (note-application nil))
  "Fetch the canonical matrix-id.lisp from cispec.org, extract the Lisp source,
   and return a string ready to write to src/matrix-id.lisp in the target repo.

   NOTE-APPLICATION, if supplied, is used to generate a header comment only;
   the module itself reads CISPEC_* from the environment at load time via env-or,
   so no interpolation into the source is required."
  (let* ((url      (cispec-url "/spec/matrix-id-lisp/"))
         (markdown (fetch-url url))
         (code     (extract-lisp-block markdown)))
    (unless code
      (error "dps/meta: could not extract Lisp code block from ~A" url))
    (str:concat
     (format nil ";;;; Generated by dps/meta from https://cispec.org/spec/matrix-id.lisp~%~
                  ;;;; cispec spec version: ~A~A~%~
                  ;;;; Do not edit — regenerate with: dps-meta~%~%"
             *cispec-spec-version*
             (if note-application
                 (format nil "~%;;;; Target application: ~A" note-application)
                 ""))
     code)))

(defun extract-lisp-block (markdown-body)
  "Extract the first ```lisp ... ``` fenced code block from MARKDOWN-BODY."
  (cl-ppcre:register-groups-bind (code)
      ("(?s)```lisp\\n(.*?)```" markdown-body)
    code))
